// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUspdRDcDJlEt6iiLmTVMkfGEYfsI4Xig',
    appId: '1:693946338720:web:4bfb61a9ffc5b257c068c5',
    messagingSenderId: '693946338720',
    projectId: 'makemyhome-27df4',
    authDomain: 'makemyhome-27df4.firebaseapp.com',
    storageBucket: 'makemyhome-27df4.appspot.com',
    measurementId: 'G-CYCEQPMWQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG5R605ffMuCxdSMgm2Am9tDsQBgkG_do',
    appId: '1:693946338720:android:4ae2019ab9511fd3c068c5',
    messagingSenderId: '693946338720',
    projectId: 'makemyhome-27df4',
    storageBucket: 'makemyhome-27df4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzfVWSaxneqqXKr5MzauafZVkK_4o7t5k',
    appId: '1:693946338720:ios:24c699656d450041c068c5',
    messagingSenderId: '693946338720',
    projectId: 'makemyhome-27df4',
    storageBucket: 'makemyhome-27df4.appspot.com',
    iosClientId: '693946338720-qd4houcnl7f4pbn5j83cq0elb5ee9f5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.makemyhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzfVWSaxneqqXKr5MzauafZVkK_4o7t5k',
    appId: '1:693946338720:ios:24c699656d450041c068c5',
    messagingSenderId: '693946338720',
    projectId: 'makemyhome-27df4',
    storageBucket: 'makemyhome-27df4.appspot.com',
    iosClientId: '693946338720-qd4houcnl7f4pbn5j83cq0elb5ee9f5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.makemyhome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUspdRDcDJlEt6iiLmTVMkfGEYfsI4Xig',
    appId: '1:693946338720:web:f78d67182a0d54e5c068c5',
    messagingSenderId: '693946338720',
    projectId: 'makemyhome-27df4',
    authDomain: 'makemyhome-27df4.firebaseapp.com',
    storageBucket: 'makemyhome-27df4.appspot.com',
    measurementId: 'G-EQECJW0WH6',
  );

}